FROM node:10.15.0 as builder

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm install

# add app
COPY . /app

# generate build
RUN npm run build-prod

FROM nginx:1.13.9-alpine

# copy artifact build from the 'build environment'
FROM nginx:alpine

COPY --from=builder /app/dist/platform-fe /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
